# options:
#    auto-update - Github 新版本自动检查并更新
#    armor-update-interval - 粘液科技护甲效果更新周期
#    enable-armor-effects - 护甲效果的开关
#    chat-prefix - 粘液科技所有消息的前缀
#    auto-save-delay-in-minutes - 自动保存数据的周期, 单位为分钟
#    legacy-ore-washer - 是否使用旧版的洗矿机机制
#    legacy-dust-washer - 是否使用旧版的除尘机机制
#    legacy-ore-grinder - 是否使用旧版的碎矿机机制
#    language - 粘液科技文本语言 (不包括物品)
#    enable-translations - 多语言功能
#    backwards-compatibility - 物品向后兼容模式, 关闭后物品会使用新版物品系统
#                             将会提升服务器性能
#    log-duplicate-block-entries - 是否输出发现重复方块的警告
#    burn-players-when-radioactive - 是否在当玩家暴露在辐射中时灼烧玩家
#    drop-excess-sf-give-items - 是否在背包已满时使用命令给予 Slimefun 物品直接掉落溢出的物品
#    backup-data - 自动备份数据
options:
  auto-update: true
  backwards-compatibility: false
  chat-prefix: '&a&lSlimefun 4 &7> '
  armor-update-interval: 10
  enable-armor-effects: true
  auto-save-delay-in-minutes: 10
  legacy-ore-washer: false
  legacy-dust-washer: false
  legacy-ore-grinder: true
  language: zh-CN
  enable-translations: true
  log-duplicate-block-entries: true
  burn-players-when-radioactive: true
  drop-excess-sf-give-items: false
  backup-data: true

guide:
  # 是否在指南中展示原版物品合成配方
  show-vanilla-recipes: true
  # 是否在玩家第一次进入服务器时自动赠送粘液科技指南
  receive-on-first-join: false
  # 是否在搜索中显示隐藏物品
  show-hidden-item-groups-in-search: false

researches:
  # 是否允许创造模式玩家免费解锁研究
  free-in-creative-mode: true
  # 是否在解锁时燃放烟花
  enable-fireworks: false
  # 是否使用游戏币替代使用经验解锁
  use-money-unlock: false
  # 经验自动转换到游戏币倍率
  currency-cost-convert-rate: 25.0
  # 是否禁用解锁研究时的动画
  disable-learning-animation: true

URID:
  info-delay: 3000
  custom-ticker-delay: 10
  enable-tickers: true

networks:
  max-size: 200
  cargo-ticker-delay: 0
  enable-visualizer: true
  delete-excess-items: false

talismans:
  use-actionbar: true

metrics:
  auto-update: false

backpack:
  # 背包所有者离线时是否允许背包被打开
  allow-open-when-owner-offline: true

research-ranks:
  - Void